### ISSUE TITLE
Whats the topic of the project

### ISSUE THREAD

**Issue by tobinski** [dataramblers/datenhack-sozarchiv#1]
What is the goal and the topic of this project?

**Comment by sschuepbach** [comment]
Hi @tobinski, the reason for the project is a call by the Sozialarchiv for experimenting / hacking with its free and publicly available data (consisting mostly of images). Projects which are delivered until end of May will take part in a small contest.

At least for me it's mainly programming for fun - hence no big thing and with sparse resources -, but if you are interested, you are of course most welcome. We're still in the brainstorming phase (see [here](https://github.com/dataramblers/datenhack-sozarchiv/wiki/Projekt-Brainstorming)). Just drop me a line in case you intend to join us, I'll gladly provide you with additional information.

**Comment by tobinski** [comment]
Hi @sschuepbach. I'm generally interested to do something. But out of the wiki page can not imagine  a project yet. I could help with api plattform, frontend and datamodel work if needed. I will read the wiki page again and think about possible use-cases.
