### ISSUE TITLE
IIIF-Viewer ins Frontend einbinden

### ISSUE THREAD

**Issue by notand** [dataramblers/datenhack-sozarchiv#2]
@sschuepbach Meine favorite Einstiegshilfen aus meinen IIIF-Recherchen:

* Tutorial inklusive OpenSeadragon-Herumspielplatz: https://iiif.github.io/training/intro-to-iiif/
* konzeptionelle IIIF-Einführung (highly recommended): http://resources.digirati.com/iiif/an-introduction-to-iiif/

Und hast du gesehen, dass @tobinski sich im [Wiki](https://github.com/dataramblers/datenhack-sozarchiv/wiki/Contributors) für Mithilfe am Frontend in Angular eingetragen hat? (sowie Interesse an API-Design und Backend)

**Comment by sschuepbach** [comment]
Hallo @notand, vielen Dank für die Hinweise! Ich habe in den letzten Tagen ein wenig mit Openseadragon und Angular experimentiert. Die Ergebnisse werde ich Anfang der nächsten Woche auf Github laden, möchte aber vorher den Code noch ein wenig aufräumen. @tobinski, vielleicht hast du ja Lust, dich in diesen Arbeiten einzuklinken?

**Comment by notand** [comment]
@sschuepbach Das habe ich fast vermutet, dass ich mit meinen OpenSeadragon-Hinweisen zu spät bin. Bin gespannt, wie das mit Angular aussieht, bin auch auf Zwischeneinsichten aus verschiedenen Experimentierphasen gespannt.

**Comment by tobinski** [comment]
@sschuepbach bitte lade doch dein Experiment hoch, dann werde ich das anschauen. Ich vermute dafür hast du das Projekt https://github.com/dataramblers/datenhack-frontend erstellt.

**Comment by sschuepbach** [comment]
Ist erledigt, @tobinski. Ich schlage vor, dass wir fortan in Feature-Branches arbeiten, via PR mergen und dann gleich Releases erstellen. So halten wir auch den Rest der Gruppe über die Entwicklungen auf dem Laufenden, ohne dass er in die einzelnen Commits schauen muss, und zudem haben wir gleich schon das Fundament für eine Doku. Was meinst du?

**Comment by sschuepbach** [comment]
@notand , i.O. für dich, wenn wir das Issue schliessen? Ich schlage vor, dass wir weitere Diskussionen technischer Details zur Einbindung in [dataramblers/datenhack-frontend](https://github.com/dataramblers/datenhack-frontend) führen.
