### ISSUE TITLE
Nutzung der "besseren" bild-video-ton-Metadaten klären

### ISSUE THREAD

**Issue by notand** [dataramblers/datenhack-sozarchiv#4]
Wenn ich das von unserem Treffen letzte Woche richtig im Kopf habe, müssen wir noch abklären, ob und mit welchen Bestimmungen wir für den ausgeschriebenen Hack die https://www.bild-video-ton.ch/ Metadaten benutzen können. Richtig? Die allgemeinen [Nutzungsbestimmungen](https://www.sozialarchiv.ch/archiv/benutzung/nutzungsbestimmungen/#c325) klingen ziemlich restriktiv. @sschuepbach Hast du den Datenhack-Flyer noch, und steht darauf eine Kontaktperson, die man dazu befragen könnte?

**Comment by sschuepbach** [comment]
Liebe @notand, ich habe das Sozialarchiv angefragt. Sobald ich mehr weiss, lasse ich es euch natürlich wissen.

**Comment by Sozialarchiv** [comment]
Wir können die Daten als CSV oder JSON aus der Datenbank ziehen.

Die Metadaten sind alle CC-0.

Die Nutzungbestimmung sind für alle Bilder, die nicht OpenData sind.

**Comment by sschuepbach** [comment]
Nutzungsbedingungen sind nun auch auf der Seite des Sozialarchivs angepasst: https://www.sozialarchiv.ch/archiv/benutzung/nutzungsbestimmungen/
