### ISSUE TITLE
Broken archiv

### ISSUE THREAD

**Issue by tobinski** [dataramblers/datenhack-sozarchiv#5]
Ich kann das Archiv mit den Bildern ([5025_sah2](https://data.stadt-zuerich.ch/dataset/sozialarchiv-sah/resource/59371d00-6333-42f6-b20e-dc711c3c0ecd?inner_span=True)) nicht entpacken. Das Archiv scheint beschädigt zu sein.

> End-of-central-directory signature not found.  Either this file is not   a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.

Ich hab es den Betreibern der gemeldet und schliesse das Ticket, sobald ein alktualisiertes Archiv verfügbar ist

**Comment by tobinski** [comment]
Sollte gefixed sein, konnte es aber noch nicht testen

---

Ich habe das von Ihnen gemeldete Zip-File gelöscht und neu unter dem Namen «5025_Fc-Fd» hochgeladen:
https://data.stadt-zuerich.ch/dataset/sozialarchiv-sah/resource/6a83e69f-b057-4b7b-90d5-91d801c564d3 
Bitte melden Sie sich, falls es erneut ein Problem damit geben würde.

---

Ich werde dies am Abend testen und den Server entsprechend anpassen

**Comment by tobinski** [comment]
Ich kann das Archiv weiterhin nicht entpacken. Weder auf meiner lokalen Maschine noch auf dem Server. Kann dies @dataramblers/owners  anderes bitte validieren?

**Comment by sschuepbach** [comment]
@tobinski, bei mir funktioniert es auch nicht. Es scheint sich aber tatsächlich um ein Zip-File zu handeln:
```
$ file 5025fc-fd.zip
5025fc-fd.zip: Zip archive data, at least v2.0 to extract
```

**Comment by sschuepbach** [comment]
Lieber @tobinski, weisst du, ob sich in dieser Sache in der Zwischenzeit noch etwas getan hat? Können wir das Issue schliessen?

**Comment by tobinski** [comment]
Das Problem besteht auf Linux weiter. Die Daten sind mir mittlerweile direkt zugestellt worden. Leider kann ich dies so nicht im Ansible Paybook hinterlegen und nicht automatisieren
