### ISSUE TITLE
Helvetosaurus-Dokumentation

### ISSUE THREAD

**Issue by Sozialarchiv** [dataramblers/datenhack-sozarchiv#8]
Eine Dokumentation und RDF-Version des Helvetosaurus steht nun online:

https://helvetosaurus.sozialarchiv.ch/
https://github.com/helvetosaurus/helvetosaurus

In den RDF-Dateien wurde der Helvetosaurus mit der GND, STW und EuroVoc gematched.

**Comment by ALedl** [comment]
Super! Wäre es möglich, zusätzlich zu den einzelnen Konzepten auch ein integriertes RDF-File anzubieten? Dann könnten wir den Helvetosaurus neben dem Eintrag https://bartoc.org/en/node/675 auch in den Vocabulary Service https://bartoc-skosmos.unibas.ch/ aufnehmen.

**Comment by Sozialarchiv** [comment]
Ja kann ich machen.

bartoc.org ist übrigens eine echt gute Seite, die sehr hilfreich ist.

**Comment by ALedl** [comment]
Perfekt! Und danke, das freut mich.

**Comment by Sozialarchiv** [comment]
Erledigt: https://github.com/helvetosaurus/helvetosaurus/commit/85d20df99db50f19f6ea26da9ad55d0ef9e47827

Die integrierte Version kann über https://helvetosaurus.sozialarchiv.ch/helvetosaurus.rdf oder über https://helvetosaurus.sozialarchiv.ch mitContent Negotiation `Accept = application/rdf+xml` abgerufen werden.

**Comment by ALedl** [comment]
Danke! Nur mit diesem Link haben wir noch Probleme wegen der Leerstelle am Schluss: "http://d-nb.info/gnd/4272502-1 ".

**Comment by Sozialarchiv** [comment]
Das sollte nicht sein ich werde mir das ansehen.

**Comment by Sozialarchiv** [comment]
https://github.com/helvetosaurus/helvetosaurus/commit/b000e0eb5da07f7424795e93fc851f71eb925da9

> Danke! Nur mit diesem Link haben wir noch Probleme wegen der Leerstelle am Schluss: "http://d-nb.info/gnd/4272502-1 ".

Sollte nun gelöst sein
